# Generated by Django 5.2.5 on 2025-08-23 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Peso aproximado en kilogramos', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Peso (kg)'),
        ),
    ]
