# Generated by Django 5.2.5 on 2025-08-23 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pet_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('specialties', models.JSONField(default=list, help_text='Lista de especialidades del profesional')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medication_dosage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dosis del medicamento'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='default_instructions',
            field=models.TextField(blank=True, help_text='Instrucciones estándar para este servicio', verbose_name='Instrucciones por defecto'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_medication',
            field=models.BooleanField(default=False, help_text='¿Requiere medicamentos? (baños medicados, desparasitación)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='instructions',
            field=models.TextField(blank=True, help_text='Indicaciones del servicio', verbose_name='Indicaciones específicas'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='observations',
            field=models.TextField(blank=True, help_text='Observaciones durante o después del servicio', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='assigned_professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professional', verbose_name='Profesional asignado'),
        ),
    ]
